name: alphabet_index_listview
description: a a-z indexed listview ,based on CustomScrollView and ListView, also provide a stick header listview.
version: 1.0.31
homepage: https://github.com/flappygod/alphabet_index_listview.git
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lpinyin: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
